# -------------------------------------------------------------------------------------------------
# The prefix for all the messages sent by the plugin
# -------------------------------------------------------------------------------------------------
Prefix: "&d&l[Collection]"

# -------------------------------------------------------------------------------------------------
# The language file to use.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The main command and it's aliases. Do not remove the first one!
# -------------------------------------------------------------------------------------------------
Command_Aliases: [collections, col]

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1